// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl77aOlz9J2iugiQrGgfToY0PcakvtHvA',
    appId: '1:124211341742:web:65eada00780d6671d3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    authDomain: 'fruitify-c3b7c.firebaseapp.com',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    measurementId: 'G-6CWMK6LSTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBaPQ_5A82zQNXpXJ1Gr_MVOK-9dSmaFg',
    appId: '1:124211341742:android:f3766e021e1b24eed3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiGOW7E69Tvt8aSxXfvsv-2N2bdW_3hUc',
    appId: '1:124211341742:ios:2fd09da782c4ddcfd3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    androidClientId: '124211341742-fp7oajp1vtvmd14i7k03jdqsmv48h5l6.apps.googleusercontent.com',
    iosClientId: '124211341742-ui31mc8c930tsbj6ravt61iamr8bllfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitifyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiGOW7E69Tvt8aSxXfvsv-2N2bdW_3hUc',
    appId: '1:124211341742:ios:2fd09da782c4ddcfd3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    androidClientId: '124211341742-fp7oajp1vtvmd14i7k03jdqsmv48h5l6.apps.googleusercontent.com',
    iosClientId: '124211341742-ui31mc8c930tsbj6ravt61iamr8bllfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitifyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOKVG1ZYgI1g_vzmo7U56MmEzprJGuGRE',
    appId: '1:124211341742:web:5944837fb074566ed3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    authDomain: 'fruitify-c3b7c.firebaseapp.com',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    measurementId: 'G-KQXGTHMNM1',
  );
}
